### ISSUE TITLE
Need to expose blob metadata in GetAsync

### ISSUE THREAD

**Issue by RPM1984** [Homely/Homely.Storage.Blobs#1]
# Problem
[This code](https://github.com/Homely/Homely.Storage.Blobs/blob/master/src/Homely.Storage.Blobs/AzureBlob.cs#L59) hides away the internal [CloudBlockBlob metadata](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.cloudblockblob?view=azure-dotnet#properties).

Such information might be useful for consumers, for example `Properties.ContentType`.

This came up because we were trying to assert that `.AddAsync` was being called with the correct content type in a test. To assert that, we needed to verify the metadata in `.GetAsync`, but it's being hidden away.

# Suggestion
Instead of returning `T` in `GetAsync`, return a class that has `T`, but also the other attributes, in case the consumer wants it.

e.g

```
public class BlobData<T>
{
   public T Model { get; set; }
   public BlobProperties Properties { get; set; }
}
```

The consumer might need _other_ metadata in `CloudBlockBlob`, but maybe we start with this?

**Comment by PureKrome** [comment]
Ok - interesting.

🤔 Ok - so how about this question first: What is the _common_ use case? I would have thought (based on experience of just 1 person -- me .. so that's a crap data statistic) that most of the time people don't care/use this info. _most_ of the time.

If that's the case, then keep the current methods (which make it easy to consume). and possibly create a second method (as in .. with a unique name) that returns the more complex type?
